brews:
  - name: bazooka
    homepage: https://github.com/aosasona/homebrew-bazooka
    tap:
      owner: aosasona
      name: homebrew-bazooka
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      386: i386
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
env_files:
  github_token: ./github_token # for local builds
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
